version: "3.8"
services:
  recaptchav2_solver:
    build: .
    ipc: "host"
    restart: always
    network_mode: host
    volumes:
      - .:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - VERSION=latest
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIE=all

    entrypoint: tail -f /bin/bash
